// components/dashboard/gallery-pagination-controls.tsx
"use client";

import {ChevronLeft, ChevronRight} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";

const PAGE_SIZE_OPTIONS = [10, 25, 50] as const;

type GalleryPaginationControlsProps = {
    totalItems: number;
    page: number;
    pageSize: 10 | 25 | 50;
    onPageChange: (page: number) => void;
    onPageSizeChange: (pageSize: 10 | 25 | 50) => void;
    disabled?: boolean;
};

export function GalleryPaginationControls({
    totalItems,
    page,
    pageSize,
    onPageChange,
    onPageSizeChange,
    disabled = false,
}: GalleryPaginationControlsProps) {
    const totalPages = Math.max(1, Math.ceil(totalItems / pageSize));
    const clampedPage = Math.min(Math.max(page, 1), totalPages);
    const from = totalItems === 0 ? 0 : (clampedPage - 1) * pageSize + 1;
    const to = Math.min(clampedPage * pageSize, totalItems);

    const canPrev = clampedPage > 1 && !disabled;
    const canNext = clampedPage < totalPages && !disabled;

    return (
        <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex flex-wrap items-center gap-2">
                <p className="text-xs text-muted-foreground">
                    Mostrando {from}-{to} de {totalItems}
                </p>
                <span className="text-xs text-muted-foreground">Solicitud:</span>
                {PAGE_SIZE_OPTIONS.map((option) => (
                    <Badge
                        key={option}
                        asChild
                        variant={option === pageSize ? "default" : "outline"}
                        className={disabled ? "opacity-60" : ""}
                    >
                        <button
                            type="button"
                            onClick={() => onPageSizeChange(option)}
                            disabled={disabled || option === pageSize}
                            className="cursor-pointer"
                        >
                            {option}
                        </button>
                    </Badge>
                ))}
            </div>

            <div className="flex items-center gap-2">
                <Button
                    size="sm"
                    variant="outline"
                    onClick={() => onPageChange(clampedPage - 1)}
                    disabled={!canPrev}
                >
                    <ChevronLeft className="h-4 w-4"/>
                    Anterior
                </Button>
                <p className="text-xs text-muted-foreground">
                    Página {clampedPage} de {totalPages}
                </p>
                <Button
                    size="sm"
                    variant="outline"
                    onClick={() => onPageChange(clampedPage + 1)}
                    disabled={!canNext}
                >
                    Siguiente
                    <ChevronRight className="h-4 w-4"/>
                </Button>
            </div>
        </div>
    );
}

// components/dashboard/GalleryPaginationControls.vue
<script setup lang="ts">
import { ChevronLeft, ChevronRight } from "lucide-vue-next";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const PAGE_SIZE_OPTIONS = [10, 25, 50] as const;

const props = withDefaults(
  defineProps<{
    totalItems: number;
    page: number;
    pageSize: 10 | 25 | 50;
    disabled?: boolean;
  }>(),
  {
    disabled: false,
  },
);

const emit = defineEmits<{
  pageChange: [page: number];
  pageSizeChange: [pageSize: 10 | 25 | 50];
}>();

const totalPages = computed(() => Math.max(1, Math.ceil(props.totalItems / props.pageSize)));
const clampedPage = computed(() => Math.min(Math.max(props.page, 1), totalPages.value));
const from = computed(() => (props.totalItems === 0 ? 0 : (clampedPage.value - 1) * props.pageSize + 1));
const to = computed(() => Math.min(clampedPage.value * props.pageSize, props.totalItems));
const canPrev = computed(() => clampedPage.value > 1 && !props.disabled);
const canNext = computed(() => clampedPage.value < totalPages.value && !props.disabled);
</script>

<template>
  <div class="flex flex-wrap items-center justify-between gap-2">
    <div class="flex flex-wrap items-center gap-2">
      <p class="text-xs text-muted-foreground">
        Mostrando {{ from }}-{{ to }} de {{ totalItems }}
      </p>
      <span class="text-xs text-muted-foreground">Solicitud:</span>
      <Badge
        v-for="option in PAGE_SIZE_OPTIONS"
        :key="option"
        :variant="option === pageSize ? 'default' : 'outline'"
        :class="disabled ? 'opacity-60' : ''"
      >
        <button
          type="button"
          class="cursor-pointer"
          :disabled="disabled || option === pageSize"
          @click="emit('pageSizeChange', option)"
        >
          {{ option }}
        </button>
      </Badge>
    </div>

    <div class="flex items-center gap-2">
      <Button
        size="sm"
        variant="outline"
        :disabled="!canPrev"
        @click="emit('pageChange', clampedPage - 1)"
      >
        <ChevronLeft class="size-4" />
        Anterior
      </Button>
      <p class="text-xs text-muted-foreground">
        Página {{ clampedPage }} de {{ totalPages }}
      </p>
      <Button
        size="sm"
        variant="outline"
        :disabled="!canNext"
        @click="emit('pageChange', clampedPage + 1)"
      >
        Siguiente
        <ChevronRight class="size-4" />
      </Button>
    </div>
  </div>
</template>
