// app/storage-test/page.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { useAuth } from "@/components/providers/auth-provider";
import { uploadFileForCurrentUserWithProgress } from "@/lib/firebase/storage";

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }

  return "No se pudo subir el archivo.";
}

export default function StorageTestPage() {
  const { user, loading, error } = useAuth();
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState(0);
  const [message, setMessage] = useState("");
  const [downloadUrl, setDownloadUrl] = useState("");

  async function handleUpload() {
    if (!file) {
      setMessage("Selecciona un archivo primero.");
      return;
    }

    setBusy(true);
    setProgress(0);
    setMessage("");
    setDownloadUrl("");

    try {
      const result = await uploadFileForCurrentUserWithProgress(file, setProgress);
      setMessage(`Archivo subido: ${result.path}`);
      setDownloadUrl(result.downloadURL);
    } catch (reason) {
      setMessage(getErrorMessage(reason));
    } finally {
      setBusy(false);
    }
  }

  return (
    <main className="mx-auto flex min-h-screen w-full max-w-3xl flex-col gap-6 px-6 py-12">
      <header className="space-y-2">
        <h1 className="text-3xl font-bold">Storage Test</h1>
        <p className="text-muted-foreground">
          Prueba subida de archivos a Firebase Storage con progreso.
        </p>
        <Link href="/" className="text-sm underline">
          Volver a la página principal
        </Link>
      </header>

      {loading ? <p>Cargando sesión...</p> : null}
      {error ? <p className="text-sm text-destructive">{error}</p> : null}
      {!loading && !user ? <p>Inicia sesión en la página principal para poder subir archivos.</p> : null}

      <section className="rounded-xl border p-6 space-y-4">
        <input
          type="file"
          onChange={(event) => setFile(event.target.files?.[0] ?? null)}
          disabled={!user || busy}
          className="block w-full text-sm"
        />
        <button
          onClick={handleUpload}
          disabled={!user || busy}
          className="rounded-md bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50"
        >
          {busy ? "Subiendo..." : "Subir archivo"}
        </button>

        <div className="h-2 w-full overflow-hidden rounded bg-muted">
          <div
            className="h-full bg-primary transition-all"
            style={{ width: `${progress}%` }}
          />
        </div>
        <p className="text-sm text-muted-foreground">{progress}%</p>

        {message ? <p className="text-sm text-muted-foreground">{message}</p> : null}
        {downloadUrl ? (
          <a className="text-sm underline" href={downloadUrl} target="_blank" rel="noreferrer">
            Abrir archivo subido
          </a>
        ) : null}
      </section>
    </main>
  );
}

// pages/storage-test.vue
<script setup lang="ts">
import { Loader2, Upload } from "lucide-vue-next"
import { uploadFileForCurrentUserWithProgress } from "@/lib/firebase/storage"

useHead({
  title: "Storage Test | davalbra",
})

const { user, loading, error } = useAuth()
const nuxtApp = useNuxtApp()

const file = ref<File | null>(null)
const busy = ref(false)
const progress = ref(0)
const message = ref("")
const downloadUrl = ref("")
const fileInput = ref<HTMLInputElement | null>(null)

const handleUpload = async () => {
  if (!file.value) {
    message.value = "Selecciona un archivo primero."
    return
  }

  if (!user.value) {
    message.value = "Debes iniciar sesión para subir archivos."
    return
  }

  if (!nuxtApp.$fbStorage) {
    message.value = "Firebase Storage no está configurado."
    return
  }

  busy.value = true
  progress.value = 0
  message.value = ""
  downloadUrl.value = ""

  try {
    const resultado = await uploadFileForCurrentUserWithProgress(
      file.value,
      (porcentaje) => {
        progress.value = porcentaje
      },
    )

    downloadUrl.value = resultado.downloadURL
    message.value = `Archivo subido: ${resultado.path}`
  } catch (reason) {
    message.value =
      reason instanceof Error ? reason.message : "No se pudo subir el archivo."
  } finally {
    busy.value = false
  }
}

const handleFileChange = () => {
  file.value = fileInput.value?.files?.[0] || null
}
</script>

<template>
  <main
    class="mx-auto flex min-h-screen w-full max-w-3xl flex-col gap-6 px-6 py-12 text-slate-100"
  >
    <header class="space-y-2">
      <h1 class="text-3xl font-bold">Storage Test</h1>
      <p class="text-slate-400">
        Prueba subida de archivos a Firebase Storage con progreso.
      </p>
      <NuxtLink to="/" class="text-sm underline"
        >Volver a la página principal</NuxtLink
      >
    </header>

    <p v-if="loading" class="text-sm text-slate-300">Cargando sesión...</p>
    <p v-if="error" class="text-sm text-rose-300">{{ error }}</p>
    <p v-if="!loading && !user" class="text-sm text-slate-300">
      Inicia sesión desde la página principal para poder subir archivos.
    </p>

    <section class="panel-shell space-y-4 p-6">
      <input
        ref="fileInput"
        type="file"
        class="block w-full text-sm"
        :disabled="!user || busy"
        @change="handleFileChange"
      />

      <button
        type="button"
        class="inline-flex min-h-11 items-center gap-2 rounded-2xl bg-[#137fec] px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"
        :disabled="!user || busy"
        @click="handleUpload"
      >
        <Loader2 v-if="busy" class="h-4 w-4 animate-spin" />
        <Upload v-else class="h-4 w-4" />
        {{ busy ? "Subiendo..." : "Subir archivo" }}
      </button>

      <div class="h-2 w-full overflow-hidden rounded-full bg-white/10">
        <div
          class="h-full bg-[#137fec] transition-all"
          :style="{ width: `${progress}%` }"
        />
      </div>
      <p class="text-sm text-slate-400">{{ progress }}%</p>

      <p v-if="message" class="text-sm text-slate-300">{{ message }}</p>
      <a
        v-if="downloadUrl"
        class="text-sm underline"
        :href="downloadUrl"
        target="_blank"
        rel="noreferrer"
      >
        Abrir archivo subido
      </a>
    </section>
  </main>
</template>
